package com.kalightortaio.veterandifficulty.datagen;

import java.util.concurrent.CompletableFuture;

import com.kalightortaio.veterandifficulty.block.ModBlocks;
import com.kalightortaio.veterandifficulty.systems.internal.ModTags;

import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricProvidedTagBuilder;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricTagProvider;
import net.minecraft.block.Blocks;
import net.minecraft.data.tag.ProvidedTagBuilder;
import net.minecraft.registry.RegistryWrapper;
import net.minecraft.registry.tag.BlockTags;

public class ModBlockTagProvider extends FabricTagProvider.BlockTagProvider {
    public ModBlockTagProvider(FabricDataOutput output, CompletableFuture<RegistryWrapper.WrapperLookup> completableFuture) {
        super(output, completableFuture);
    }

    @Override
    protected void configure(RegistryWrapper.WrapperLookup wrapperLookup) {
        valueLookupBuilder(ModTags.GLASS_PANES)
        .add(Blocks.GLASS_PANE)
        .add(Blocks.BLACK_STAINED_GLASS_PANE)
        .add(Blocks.BLUE_STAINED_GLASS_PANE)
        .add(Blocks.BROWN_STAINED_GLASS_PANE)
        .add(Blocks.CYAN_STAINED_GLASS_PANE)
        .add(Blocks.GRAY_STAINED_GLASS_PANE)
        .add(Blocks.GREEN_STAINED_GLASS_PANE)
        .add(Blocks.LIGHT_BLUE_STAINED_GLASS_PANE)
        .add(Blocks.LIGHT_GRAY_STAINED_GLASS_PANE)
        .add(Blocks.LIME_STAINED_GLASS_PANE)
        .add(Blocks.MAGENTA_STAINED_GLASS_PANE)
        .add(Blocks.ORANGE_STAINED_GLASS_PANE)
        .add(Blocks.PINK_STAINED_GLASS_PANE)
        .add(Blocks.PURPLE_STAINED_GLASS_PANE)
        .add(Blocks.RED_STAINED_GLASS_PANE)
        .add(Blocks.WHITE_STAINED_GLASS_PANE)
        .add(Blocks.YELLOW_STAINED_GLASS_PANE);

        /*valueLookupBuilder(ModTags.NEEDS_NO_TOOL)
        .addOptionalTag(BlockTags.CANDLES)
        .addOptionalTag(BlockTags.CANDLE_CAKES)
        .addOptionalTag(BlockTags.BEE_GROWABLES)
        .addOptionalTag(BlockTags.ENDERMAN_HOLDABLE)
        .addOptionalTag(BlockTags.WART_BLOCKS)
        .addOptionalTag(BlockTags.FIRE)
        .addOptionalTag(BlockTags.FLOWERS)
        .addOptionalTag(BlockTags.FLOWER_POTS)
        .addOptionalTag(BlockTags.CAMPFIRES)
        .addOptionalTag(BlockTags.HOE_MINEABLE)
        .addOptionalTag(BlockTags.SHOVEL_MINEABLE)
        .addOptionalTag(BlockTags.WARPED_STEMS)
        .addOptionalTag(BlockTags.WOOL)
        .addOptionalTag(BlockTags.WOOL_CARPETS)
        .addOptionalTag(BlockTags.BANNERS)
        .addOptionalTag(BlockTags.ALL_SIGNS)
        .addOptionalTag(BlockTags.EDIBLE_FOR_SHEEP)
        .addOptionalTag(BlockTags.IMPERMEABLE)
        .addOptionalTag(BlockTags.SWORD_EFFICIENT)
        .addOptionalTag(BlockTags.INSIDE_STEP_SOUND_BLOCKS)
        .addOptionalTag(BlockTags.COMBINATION_STEP_SOUND_BLOCKS)
        .addOptionalTag(BlockTags.CLIMBABLE)
        .addOptionalTag(BlockTags.CORAL_PLANTS)
        .addOptionalTag(BlockTags.REPLACEABLE_BY_TREES)
        .addTag(ModTags.GLASS_PANES)
        .add(Blocks.REDSTONE_WIRE)
        .add(Blocks.REPEATER)
        .add(Blocks.COMPARATOR)
        .add(Blocks.REDSTONE_TORCH)
        .add(Blocks.REDSTONE_WALL_TORCH)
        .add(Blocks.TORCH)
        .add(Blocks.WALL_TORCH)
        .add(Blocks.SOUL_TORCH)
        .add(Blocks.SOUL_WALL_TORCH)
        .add(Blocks.KELP)
        .add(Blocks.KELP_PLANT)
        .add(Blocks.SEAGRASS)
        .add(Blocks.SEA_PICKLE)
        .add(Blocks.TALL_SEAGRASS)
        .add(Blocks.SLIME_BLOCK)
        .add(Blocks.HONEYCOMB_BLOCK)
        .add(Blocks.HONEY_BLOCK)
        .add(Blocks.FROGSPAWN)
        .add(Blocks.PEARLESCENT_FROGLIGHT)
        .add(Blocks.VERDANT_FROGLIGHT)
        .add(Blocks.OCHRE_FROGLIGHT)
        .add(Blocks.SUGAR_CANE)
        .add(Blocks.TURTLE_EGG)
        .add(Blocks.END_ROD)
        .add(Blocks.NETHER_WART)
        .add(Blocks.CRIMSON_FUNGUS)
        .add(Blocks.WARPED_FUNGUS)
        .add(Blocks.CACTUS)
        .add(Blocks.RED_MUSHROOM_BLOCK)
        .add(Blocks.BROWN_MUSHROOM_BLOCK)
        .add(Blocks.CAKE)
        .add(Blocks.BAMBOO);
        */

        valueLookupBuilder(ModTags.NEEDS_FLINT_TOOL)
        .addOptionalTag(BlockTags.LOGS)
        .addOptionalTag(BlockTags.PLANKS)
        .addOptionalTag(BlockTags.SAPLINGS)
        .addOptionalTag(BlockTags.DIRT)
        .addOptionalTag(BlockTags.CROPS)
        .addOptionalTag(BlockTags.ICE)
        .add(
            Blocks.CLAY,
            Blocks.PACKED_MUD,
            Blocks.MUD_BRICKS,
            Blocks.MUD_BRICK_SLAB,
            Blocks.MUD_BRICK_STAIRS,
            Blocks.MUD_BRICK_WALL,
            Blocks.COAL_ORE,
            Blocks.CRAFTING_TABLE,
            Blocks.BAMBOO,
            Blocks.MELON,
            Blocks.PUMPKIN,
            Blocks.CARVED_PUMPKIN
        );

        valueLookupBuilder(ModTags.NEEDS_WOODEN_TOOL)
        .add(
            Blocks.STONE,
            Blocks.GRANITE,
            Blocks.POLISHED_GRANITE,
            Blocks.DIORITE,
            Blocks.POLISHED_DIORITE,
            Blocks.ANDESITE,
            Blocks.POLISHED_ANDESITE,
            Blocks.COBBLESTONE,
            Blocks.SANDSTONE,
            Blocks.CHISELED_SANDSTONE,
            Blocks.CUT_SANDSTONE,
            Blocks.SANDSTONE_STAIRS,
            Blocks.DISPENSER,
            Blocks.BRICKS,
            Blocks.MOSSY_COBBLESTONE,
            Blocks.FURNACE,
            Blocks.COBBLESTONE_STAIRS,
            Blocks.STONE_PRESSURE_PLATE,
            Blocks.NETHERRACK,
            Blocks.BASALT,
            Blocks.SMOOTH_BASALT,
            Blocks.POLISHED_BASALT,
            Blocks.STONE_BRICKS,
            Blocks.MOSSY_STONE_BRICKS,
            Blocks.CRACKED_STONE_BRICKS,
            Blocks.CHISELED_STONE_BRICKS,
            Blocks.BRICK_STAIRS,
            Blocks.STONE_BRICK_STAIRS,
            Blocks.NETHER_BRICKS,
            Blocks.NETHER_BRICK_FENCE,
            Blocks.NETHER_BRICK_STAIRS,
            Blocks.END_STONE,
            Blocks.DROPPER,
            Blocks.NETHER_QUARTZ_ORE,
            Blocks.QUARTZ_BLOCK,
            Blocks.CHISELED_QUARTZ_BLOCK,
            Blocks.QUARTZ_PILLAR,
            Blocks.QUARTZ_STAIRS,
            Blocks.REDSTONE_BLOCK,
            Blocks.WHITE_TERRACOTTA,
            Blocks.ORANGE_TERRACOTTA,
            Blocks.MAGENTA_TERRACOTTA,
            Blocks.LIGHT_BLUE_TERRACOTTA,
            Blocks.YELLOW_TERRACOTTA,
            Blocks.LIME_TERRACOTTA,
            Blocks.PINK_TERRACOTTA,
            Blocks.GRAY_TERRACOTTA,
            Blocks.LIGHT_GRAY_TERRACOTTA,
            Blocks.CYAN_TERRACOTTA,
            Blocks.PURPLE_TERRACOTTA,
            Blocks.BLUE_TERRACOTTA,
            Blocks.BROWN_TERRACOTTA,
            Blocks.GREEN_TERRACOTTA,
            Blocks.RED_TERRACOTTA,
            Blocks.BLACK_TERRACOTTA,
            Blocks.PRISMARINE,
            Blocks.PRISMARINE_BRICKS,
            Blocks.DARK_PRISMARINE,
            Blocks.PRISMARINE_STAIRS,
            Blocks.PRISMARINE_BRICK_STAIRS,
            Blocks.DARK_PRISMARINE_STAIRS,
            Blocks.PRISMARINE_SLAB,
            Blocks.PRISMARINE_BRICK_SLAB,
            Blocks.DARK_PRISMARINE_SLAB,
            Blocks.TERRACOTTA,
            Blocks.COAL_BLOCK,
            Blocks.RED_SANDSTONE,
            Blocks.CHISELED_RED_SANDSTONE,
            Blocks.CUT_RED_SANDSTONE,
            Blocks.RED_SANDSTONE_STAIRS,
            Blocks.STONE_SLAB,
            Blocks.SMOOTH_STONE_SLAB,
            Blocks.SANDSTONE_SLAB,
            Blocks.CUT_SANDSTONE_SLAB,
            Blocks.PETRIFIED_OAK_SLAB,
            Blocks.COBBLESTONE_SLAB,
            Blocks.BRICK_SLAB,
            Blocks.STONE_BRICK_SLAB,
            Blocks.NETHER_BRICK_SLAB,
            Blocks.QUARTZ_SLAB,
            Blocks.RED_SANDSTONE_SLAB,
            Blocks.CUT_RED_SANDSTONE_SLAB,
            Blocks.PURPUR_SLAB,
            Blocks.SMOOTH_STONE,
            Blocks.SMOOTH_SANDSTONE,
            Blocks.SMOOTH_QUARTZ,
            Blocks.SMOOTH_RED_SANDSTONE,
            Blocks.PURPUR_BLOCK,
            Blocks.PURPUR_PILLAR,
            Blocks.PURPUR_STAIRS,
            Blocks.END_STONE_BRICKS,
            Blocks.MAGMA_BLOCK,
            Blocks.RED_NETHER_BRICKS,
            Blocks.BONE_BLOCK,
            Blocks.OBSERVER,
            Blocks.WHITE_GLAZED_TERRACOTTA,
            Blocks.ORANGE_GLAZED_TERRACOTTA,
            Blocks.MAGENTA_GLAZED_TERRACOTTA,
            Blocks.LIGHT_BLUE_GLAZED_TERRACOTTA,
            Blocks.YELLOW_GLAZED_TERRACOTTA,
            Blocks.LIME_GLAZED_TERRACOTTA,
            Blocks.PINK_GLAZED_TERRACOTTA,
            Blocks.GRAY_GLAZED_TERRACOTTA,
            Blocks.LIGHT_GRAY_GLAZED_TERRACOTTA,
            Blocks.CYAN_GLAZED_TERRACOTTA,
            Blocks.PURPLE_GLAZED_TERRACOTTA,
            Blocks.BLUE_GLAZED_TERRACOTTA,
            Blocks.BROWN_GLAZED_TERRACOTTA,
            Blocks.GREEN_GLAZED_TERRACOTTA,
            Blocks.RED_GLAZED_TERRACOTTA,
            Blocks.BLACK_GLAZED_TERRACOTTA,
            Blocks.WHITE_CONCRETE,
            Blocks.ORANGE_CONCRETE,
            Blocks.MAGENTA_CONCRETE,
            Blocks.LIGHT_BLUE_CONCRETE,
            Blocks.YELLOW_CONCRETE,
            Blocks.LIME_CONCRETE,
            Blocks.PINK_CONCRETE,
            Blocks.GRAY_CONCRETE,
            Blocks.LIGHT_GRAY_CONCRETE,
            Blocks.CYAN_CONCRETE,
            Blocks.PURPLE_CONCRETE,
            Blocks.BLUE_CONCRETE,
            Blocks.BROWN_CONCRETE,
            Blocks.GREEN_CONCRETE,
            Blocks.RED_CONCRETE,
            Blocks.BLACK_CONCRETE,
            Blocks.DEAD_TUBE_CORAL_BLOCK,
            Blocks.DEAD_BRAIN_CORAL_BLOCK,
            Blocks.DEAD_BUBBLE_CORAL_BLOCK,
            Blocks.DEAD_FIRE_CORAL_BLOCK,
            Blocks.DEAD_HORN_CORAL_BLOCK,
            Blocks.TUBE_CORAL_BLOCK,
            Blocks.BRAIN_CORAL_BLOCK,
            Blocks.BUBBLE_CORAL_BLOCK,
            Blocks.FIRE_CORAL_BLOCK,
            Blocks.HORN_CORAL_BLOCK,
            Blocks.DEAD_TUBE_CORAL,
            Blocks.DEAD_BRAIN_CORAL,
            Blocks.DEAD_BUBBLE_CORAL,
            Blocks.DEAD_FIRE_CORAL,
            Blocks.DEAD_HORN_CORAL,
            Blocks.DEAD_TUBE_CORAL_FAN,
            Blocks.DEAD_BRAIN_CORAL_FAN,
            Blocks.DEAD_BUBBLE_CORAL_FAN,
            Blocks.DEAD_FIRE_CORAL_FAN,
            Blocks.DEAD_HORN_CORAL_FAN,
            Blocks.DEAD_TUBE_CORAL_WALL_FAN,
            Blocks.DEAD_BRAIN_CORAL_WALL_FAN,
            Blocks.DEAD_BUBBLE_CORAL_WALL_FAN,
            Blocks.DEAD_FIRE_CORAL_WALL_FAN,
            Blocks.DEAD_HORN_CORAL_WALL_FAN,
            Blocks.POLISHED_GRANITE_STAIRS,
            Blocks.SMOOTH_RED_SANDSTONE_STAIRS,
            Blocks.MOSSY_STONE_BRICK_STAIRS,
            Blocks.POLISHED_DIORITE_STAIRS,
            Blocks.MOSSY_COBBLESTONE_STAIRS,
            Blocks.END_STONE_BRICK_STAIRS,
            Blocks.STONE_STAIRS,
            Blocks.SMOOTH_SANDSTONE_STAIRS,
            Blocks.SMOOTH_QUARTZ_STAIRS,
            Blocks.GRANITE_STAIRS,
            Blocks.ANDESITE_STAIRS,
            Blocks.RED_NETHER_BRICK_STAIRS,
            Blocks.POLISHED_ANDESITE_STAIRS,
            Blocks.DIORITE_STAIRS,
            Blocks.POLISHED_GRANITE_SLAB,
            Blocks.SMOOTH_RED_SANDSTONE_SLAB,
            Blocks.MOSSY_STONE_BRICK_SLAB,
            Blocks.POLISHED_DIORITE_SLAB,
            Blocks.MOSSY_COBBLESTONE_SLAB,
            Blocks.END_STONE_BRICK_SLAB,
            Blocks.SMOOTH_SANDSTONE_SLAB,
            Blocks.SMOOTH_QUARTZ_SLAB,
            Blocks.GRANITE_SLAB,
            Blocks.ANDESITE_SLAB,
            Blocks.RED_NETHER_BRICK_SLAB,
            Blocks.POLISHED_ANDESITE_SLAB,
            Blocks.DIORITE_SLAB,
            Blocks.SMOKER,
            Blocks.BLAST_FURNACE,
            Blocks.GRINDSTONE,
            Blocks.STONECUTTER,
            Blocks.WARPED_NYLIUM,
            Blocks.CRIMSON_NYLIUM,
            Blocks.BLACKSTONE,
            Blocks.BLACKSTONE_STAIRS,
            Blocks.BLACKSTONE_SLAB,
            Blocks.POLISHED_BLACKSTONE,
            Blocks.POLISHED_BLACKSTONE_BRICKS,
            Blocks.CRACKED_POLISHED_BLACKSTONE_BRICKS,
            Blocks.CHISELED_POLISHED_BLACKSTONE,
            Blocks.POLISHED_BLACKSTONE_BRICK_SLAB,
            Blocks.POLISHED_BLACKSTONE_BRICK_STAIRS,
            Blocks.POLISHED_BLACKSTONE_STAIRS,
            Blocks.POLISHED_BLACKSTONE_SLAB,
            Blocks.POLISHED_BLACKSTONE_PRESSURE_PLATE,
            Blocks.CHISELED_NETHER_BRICKS,
            Blocks.CRACKED_NETHER_BRICKS,
            Blocks.QUARTZ_BRICKS,
            Blocks.TUFF,
            Blocks.CALCITE,
            Blocks.POINTED_DRIPSTONE,
            Blocks.DRIPSTONE_BLOCK,
            Blocks.PISTON,
            Blocks.STICKY_PISTON,
            Blocks.PISTON_HEAD,
            Blocks.AMETHYST_CLUSTER,
            Blocks.SMALL_AMETHYST_BUD,
            Blocks.MEDIUM_AMETHYST_BUD,
            Blocks.LARGE_AMETHYST_BUD,
            Blocks.AMETHYST_BLOCK,
            Blocks.BUDDING_AMETHYST,
            Blocks.INFESTED_COBBLESTONE,
            Blocks.INFESTED_CHISELED_STONE_BRICKS,
            Blocks.INFESTED_CRACKED_STONE_BRICKS,
            Blocks.INFESTED_DEEPSLATE,
            Blocks.INFESTED_STONE,
            Blocks.INFESTED_MOSSY_STONE_BRICKS,
            Blocks.INFESTED_STONE_BRICKS,
            Blocks.TUFF_SLAB,
            Blocks.TUFF_STAIRS,
            Blocks.TUFF_WALL,
            Blocks.CHISELED_TUFF,
            Blocks.POLISHED_TUFF,
            Blocks.POLISHED_TUFF_SLAB,
            Blocks.POLISHED_TUFF_STAIRS,
            Blocks.POLISHED_TUFF_WALL,
            Blocks.TUFF_BRICKS,
            Blocks.TUFF_BRICK_SLAB,
            Blocks.TUFF_BRICK_STAIRS,
            Blocks.TUFF_BRICK_WALL,
            Blocks.CHISELED_TUFF_BRICKS,
            Blocks.RESIN_BRICKS,
            Blocks.RESIN_BRICK_SLAB,
            Blocks.RESIN_BRICK_WALL,
            Blocks.RESIN_BRICK_STAIRS,
            Blocks.CHISELED_RESIN_BRICKS
        )
        .addOptionalTag(BlockTags.STONE_BUTTONS)
        .addOptionalTag(BlockTags.WALLS)
        .addOptionalTag(BlockTags.SHULKER_BOXES);


        replace(valueLookupBuilder(BlockTags.NEEDS_STONE_TOOL))
        .add(
            Blocks.CRAFTER,
            Blocks.LODESTONE,
            Blocks.BELL,
            Blocks.LANTERN,
            Blocks.SOUL_LANTERN,
            Blocks.IRON_TRAPDOOR,
            Blocks.LIGHT_WEIGHTED_PRESSURE_PLATE,
            Blocks.HEAVY_WEIGHTED_PRESSURE_PLATE,
            Blocks.ENCHANTING_TABLE,
            Blocks.BREWING_STAND,
            Blocks.IRON_BARS,
            Blocks.CHAIN,
            Blocks.SPAWNER,
            Blocks.OXIDIZED_COPPER,
            Blocks.WEATHERED_COPPER,
            Blocks.EXPOSED_COPPER,
            Blocks.RAW_COPPER_BLOCK,
            Blocks.COPPER_BLOCK,
            Blocks.COPPER_ORE,
            Blocks.CUT_COPPER_SLAB,
            Blocks.CUT_COPPER_STAIRS,
            Blocks.CUT_COPPER,
            Blocks.WEATHERED_COPPER,
            Blocks.WEATHERED_CUT_COPPER_SLAB,
            Blocks.WEATHERED_CUT_COPPER_STAIRS,
            Blocks.WEATHERED_CUT_COPPER,
            Blocks.OXIDIZED_COPPER,
            Blocks.OXIDIZED_CUT_COPPER_SLAB,
            Blocks.OXIDIZED_CUT_COPPER_STAIRS,
            Blocks.OXIDIZED_CUT_COPPER,
            Blocks.EXPOSED_COPPER,
            Blocks.EXPOSED_CUT_COPPER_SLAB,
            Blocks.EXPOSED_CUT_COPPER_STAIRS,
            Blocks.EXPOSED_CUT_COPPER,
            Blocks.WAXED_COPPER_BLOCK,
            Blocks.WAXED_CUT_COPPER_SLAB,
            Blocks.WAXED_CUT_COPPER_STAIRS,
            Blocks.WAXED_CUT_COPPER,
            Blocks.WAXED_WEATHERED_COPPER,
            Blocks.WAXED_WEATHERED_CUT_COPPER_SLAB,
            Blocks.WAXED_WEATHERED_CUT_COPPER_STAIRS,
            Blocks.WAXED_WEATHERED_CUT_COPPER,
            Blocks.WAXED_EXPOSED_COPPER,
            Blocks.WAXED_EXPOSED_CUT_COPPER_SLAB,
            Blocks.WAXED_EXPOSED_CUT_COPPER_STAIRS,
            Blocks.WAXED_EXPOSED_CUT_COPPER,
            Blocks.WAXED_OXIDIZED_COPPER,
            Blocks.WAXED_OXIDIZED_CUT_COPPER_SLAB,
            Blocks.WAXED_OXIDIZED_CUT_COPPER_STAIRS,
            Blocks.WAXED_OXIDIZED_CUT_COPPER,
            Blocks.LIGHTNING_ROD,
            Blocks.CHISELED_COPPER,
            Blocks.EXPOSED_CHISELED_COPPER,
            Blocks.WEATHERED_CHISELED_COPPER,
            Blocks.OXIDIZED_CHISELED_COPPER,
            Blocks.WAXED_CHISELED_COPPER,
            Blocks.WAXED_EXPOSED_CHISELED_COPPER,
            Blocks.WAXED_WEATHERED_CHISELED_COPPER,
            Blocks.WAXED_OXIDIZED_CHISELED_COPPER,
            Blocks.CHISELED_COPPER,
            Blocks.EXPOSED_CHISELED_COPPER,
            Blocks.WEATHERED_CHISELED_COPPER,
            Blocks.OXIDIZED_CHISELED_COPPER,
            Blocks.WAXED_CHISELED_COPPER,
            Blocks.WAXED_EXPOSED_CHISELED_COPPER,
            Blocks.WAXED_WEATHERED_CHISELED_COPPER,
            Blocks.WAXED_OXIDIZED_CHISELED_COPPER,
            Blocks.COPPER_GRATE,
            Blocks.EXPOSED_COPPER_GRATE,
            Blocks.WEATHERED_COPPER_GRATE,
            Blocks.OXIDIZED_COPPER_GRATE,
            Blocks.WAXED_COPPER_GRATE,
            Blocks.WAXED_EXPOSED_COPPER_GRATE,
            Blocks.WAXED_WEATHERED_COPPER_GRATE,
            Blocks.WAXED_OXIDIZED_COPPER_GRATE,
            Blocks.COPPER_BULB,
            Blocks.EXPOSED_COPPER_BULB,
            Blocks.WEATHERED_COPPER_BULB,
            Blocks.OXIDIZED_COPPER_BULB,
            Blocks.WAXED_COPPER_BULB,
            Blocks.WAXED_EXPOSED_COPPER_BULB,
            Blocks.WAXED_WEATHERED_COPPER_BULB,
            Blocks.WAXED_OXIDIZED_COPPER_BULB,
            Blocks.COPPER_DOOR,
            Blocks.EXPOSED_COPPER_DOOR,
            Blocks.WEATHERED_COPPER_DOOR,
            Blocks.OXIDIZED_COPPER_DOOR,
            Blocks.WAXED_COPPER_DOOR,
            Blocks.WAXED_EXPOSED_COPPER_DOOR,
            Blocks.WAXED_WEATHERED_COPPER_DOOR,
            Blocks.WAXED_OXIDIZED_COPPER_DOOR,
            Blocks.COPPER_TRAPDOOR,
            Blocks.EXPOSED_COPPER_TRAPDOOR,
            Blocks.WEATHERED_COPPER_TRAPDOOR,
            Blocks.OXIDIZED_COPPER_TRAPDOOR,
            Blocks.WAXED_COPPER_TRAPDOOR,
            Blocks.WAXED_EXPOSED_COPPER_TRAPDOOR,
            Blocks.WAXED_WEATHERED_COPPER_TRAPDOOR,
            Blocks.WAXED_OXIDIZED_COPPER_TRAPDOOR,
            Blocks.CONDUIT,
            Blocks.HEAVY_CORE
        )
        .addOptionalTag(BlockTags.ANVIL)
        .addOptionalTag(BlockTags.CAULDRONS)
        .addOptionalTag(BlockTags.RAILS);

        valueLookupBuilder(ModTags.NEEDS_COPPER_TOOL)
        .add(
            ModBlocks.SILVER_BLOCK,
            ModBlocks.SILVER_ORE,
            Blocks.REDSTONE_ORE,
            Blocks.EMERALD_ORE,
            Blocks.EMERALD_BLOCK,
            Blocks.LAPIS_BLOCK,
            Blocks.LAPIS_ORE
        );

        valueLookupBuilder(ModTags.NEEDS_SILVER_TOOL)
        .add(
            Blocks.RAW_GOLD_BLOCK,
            Blocks.GOLD_BLOCK,
            Blocks.GOLD_ORE,
            Blocks.GILDED_BLACKSTONE,
            Blocks.NETHER_GOLD_ORE
        );

        valueLookupBuilder(ModTags.NEEDS_GOLD_TOOL)
        .add(
            Blocks.DEEPSLATE_COPPER_ORE,
            Blocks.DEEPSLATE_EMERALD_ORE,
            Blocks.DEEPSLATE_REDSTONE_ORE,
            Blocks.DEEPSLATE_GOLD_ORE,
            Blocks.DEEPSLATE_COAL_ORE,
            Blocks.DEEPSLATE_LAPIS_ORE,
            Blocks.IRON_BLOCK,
            Blocks.RAW_IRON_BLOCK,
            Blocks.IRON_ORE,
            Blocks.DEEPSLATE_IRON_ORE,
            Blocks.HOPPER,
            Blocks.DEEPSLATE,
            Blocks.COBBLED_DEEPSLATE,
            Blocks.COBBLED_DEEPSLATE_STAIRS,
            Blocks.COBBLED_DEEPSLATE_SLAB,
            Blocks.POLISHED_DEEPSLATE,
            Blocks.POLISHED_DEEPSLATE_STAIRS,
            Blocks.POLISHED_DEEPSLATE_SLAB,
            Blocks.DEEPSLATE_TILES,
            Blocks.DEEPSLATE_TILE_STAIRS,
            Blocks.DEEPSLATE_TILE_SLAB,
            Blocks.DEEPSLATE_BRICKS,
            Blocks.DEEPSLATE_BRICK_STAIRS,
            Blocks.DEEPSLATE_BRICK_SLAB,
            Blocks.CHISELED_DEEPSLATE,
            Blocks.CRACKED_DEEPSLATE_BRICKS,
            Blocks.CRACKED_DEEPSLATE_TILES
        );

        replace(valueLookupBuilder(BlockTags.NEEDS_IRON_TOOL))
        .add(
            ModBlocks.MITHRIL_BLOCK,
            ModBlocks.DEEPSLATE_MITHRIL_ORE
        );

        valueLookupBuilder(ModTags.NEEDS_MITHRIL_TOOL)
        .add(
            Blocks.DIAMOND_BLOCK,
            Blocks.DIAMOND_ORE,
            Blocks.DEEPSLATE_DIAMOND_ORE
        );

        replace(valueLookupBuilder(BlockTags.NEEDS_DIAMOND_TOOL))
        .add(
            Blocks.NETHERITE_BLOCK,
            Blocks.ANCIENT_DEBRIS,
            Blocks.OBSIDIAN, 
            Blocks.CRYING_OBSIDIAN,
            Blocks.RESPAWN_ANCHOR,
            Blocks.ENDER_CHEST
        );

        valueLookupBuilder(ModTags.NEEDS_NETHERITE_TOOL)
        .add(
            ModBlocks.ENDERIUM_BLOCK,
            ModBlocks.ENDERIUM_ORE
        );

        valueLookupBuilder(ModTags.NEEDS_ENDERIUM_TOOL)
        .add(
            ModBlocks.ENDERIUM_BLOCK,
            ModBlocks.ENDERIUM_ORE
        );

        valueLookupBuilder(ModTags.NEEDS_TENEBRIS_TOOL)
        .add(Blocks.BEDROCK);

        valueLookupBuilder(ModTags.NEEDS_ZENITH_TOOL);

        valueLookupBuilder(ModTags.INCORRECT_FOR_NO_TOOL)
        .addOptionalTag(ModTags.NEEDS_FLINT_TOOL)
        .addOptionalTag(ModTags.NEEDS_WOODEN_TOOL)
        .addOptionalTag(BlockTags.NEEDS_STONE_TOOL)
        .addOptionalTag(ModTags.NEEDS_COPPER_TOOL)
        .addOptionalTag(ModTags.NEEDS_SILVER_TOOL)
        .addOptionalTag(ModTags.NEEDS_GOLD_TOOL)
        .addOptionalTag(BlockTags.NEEDS_IRON_TOOL)
        .addOptionalTag(ModTags.NEEDS_MITHRIL_TOOL)
        .addOptionalTag(BlockTags.NEEDS_DIAMOND_TOOL)
        .addOptionalTag(ModTags.NEEDS_NETHERITE_TOOL)
        .addOptionalTag(ModTags.NEEDS_ENDERIUM_TOOL)
        .addOptionalTag(ModTags.NEEDS_TENEBRIS_TOOL)
        .addOptionalTag(ModTags.NEEDS_ZENITH_TOOL);

        valueLookupBuilder(ModTags.INCORRECT_FOR_FLINT_TOOL)
        .addOptionalTag(ModTags.NEEDS_WOODEN_TOOL)
        .addOptionalTag(BlockTags.NEEDS_STONE_TOOL)
        .addOptionalTag(ModTags.NEEDS_COPPER_TOOL)
        .addOptionalTag(ModTags.NEEDS_SILVER_TOOL)
        .addOptionalTag(ModTags.NEEDS_GOLD_TOOL)
        .addOptionalTag(BlockTags.NEEDS_IRON_TOOL)
        .addOptionalTag(ModTags.NEEDS_MITHRIL_TOOL)
        .addOptionalTag(BlockTags.NEEDS_DIAMOND_TOOL)
        .addOptionalTag(ModTags.NEEDS_NETHERITE_TOOL)
        .addOptionalTag(ModTags.NEEDS_ENDERIUM_TOOL)
        .addOptionalTag(ModTags.NEEDS_TENEBRIS_TOOL)
        .addOptionalTag(ModTags.NEEDS_ZENITH_TOOL);

        replace(valueLookupBuilder(BlockTags.INCORRECT_FOR_WOODEN_TOOL))
        .addOptionalTag(BlockTags.NEEDS_STONE_TOOL)
        .addOptionalTag(ModTags.NEEDS_COPPER_TOOL)
        .addOptionalTag(ModTags.NEEDS_SILVER_TOOL)
        .addOptionalTag(ModTags.NEEDS_GOLD_TOOL)
        .addOptionalTag(BlockTags.NEEDS_IRON_TOOL)
        .addOptionalTag(ModTags.NEEDS_MITHRIL_TOOL)
        .addOptionalTag(BlockTags.NEEDS_DIAMOND_TOOL)
        .addOptionalTag(ModTags.NEEDS_NETHERITE_TOOL)
        .addOptionalTag(ModTags.NEEDS_ENDERIUM_TOOL)
        .addOptionalTag(ModTags.NEEDS_TENEBRIS_TOOL)
        .addOptionalTag(ModTags.NEEDS_ZENITH_TOOL);

        replace(valueLookupBuilder(BlockTags.INCORRECT_FOR_STONE_TOOL))
        .addOptionalTag(ModTags.NEEDS_COPPER_TOOL)
        .addOptionalTag(ModTags.NEEDS_SILVER_TOOL)
        .addOptionalTag(ModTags.NEEDS_GOLD_TOOL)
        .addOptionalTag(BlockTags.NEEDS_IRON_TOOL)
        .addOptionalTag(ModTags.NEEDS_MITHRIL_TOOL)
        .addOptionalTag(BlockTags.NEEDS_DIAMOND_TOOL)
        .addOptionalTag(ModTags.NEEDS_NETHERITE_TOOL)
        .addOptionalTag(ModTags.NEEDS_ENDERIUM_TOOL)
        .addOptionalTag(ModTags.NEEDS_TENEBRIS_TOOL)
        .addOptionalTag(ModTags.NEEDS_ZENITH_TOOL);

        valueLookupBuilder(ModTags.INCORRECT_FOR_COPPER_TOOL)
        .addOptionalTag(ModTags.NEEDS_SILVER_TOOL)
        .addOptionalTag(ModTags.NEEDS_GOLD_TOOL)
        .addOptionalTag(BlockTags.NEEDS_IRON_TOOL)
        .addOptionalTag(ModTags.NEEDS_MITHRIL_TOOL)
        .addOptionalTag(BlockTags.NEEDS_DIAMOND_TOOL)
        .addOptionalTag(ModTags.NEEDS_NETHERITE_TOOL)
        .addOptionalTag(ModTags.NEEDS_ENDERIUM_TOOL)
        .addOptionalTag(ModTags.NEEDS_TENEBRIS_TOOL)
        .addOptionalTag(ModTags.NEEDS_ZENITH_TOOL);

        valueLookupBuilder(ModTags.INCORRECT_FOR_SILVER_TOOL)
        .addOptionalTag(ModTags.NEEDS_GOLD_TOOL)
        .addOptionalTag(BlockTags.NEEDS_IRON_TOOL)
        .addOptionalTag(ModTags.NEEDS_MITHRIL_TOOL)
        .addOptionalTag(BlockTags.NEEDS_DIAMOND_TOOL)
        .addOptionalTag(ModTags.NEEDS_NETHERITE_TOOL)
        .addOptionalTag(ModTags.NEEDS_ENDERIUM_TOOL)
        .addOptionalTag(ModTags.NEEDS_TENEBRIS_TOOL)
        .addOptionalTag(ModTags.NEEDS_ZENITH_TOOL);
        
        replace(valueLookupBuilder(BlockTags.INCORRECT_FOR_GOLD_TOOL))
        .addOptionalTag(BlockTags.NEEDS_IRON_TOOL)
        .addOptionalTag(ModTags.NEEDS_MITHRIL_TOOL)
        .addOptionalTag(BlockTags.NEEDS_DIAMOND_TOOL)
        .addOptionalTag(ModTags.NEEDS_NETHERITE_TOOL)
        .addOptionalTag(ModTags.NEEDS_ENDERIUM_TOOL)
        .addOptionalTag(ModTags.NEEDS_TENEBRIS_TOOL)
        .addOptionalTag(ModTags.NEEDS_ZENITH_TOOL);

        replace(valueLookupBuilder(BlockTags.INCORRECT_FOR_IRON_TOOL))
        .addOptionalTag(ModTags.NEEDS_MITHRIL_TOOL)
        .addOptionalTag(BlockTags.NEEDS_DIAMOND_TOOL)
        .addOptionalTag(ModTags.NEEDS_NETHERITE_TOOL)
        .addOptionalTag(ModTags.NEEDS_ENDERIUM_TOOL)
        .addOptionalTag(ModTags.NEEDS_TENEBRIS_TOOL)
        .addOptionalTag(ModTags.NEEDS_ZENITH_TOOL);

        valueLookupBuilder(ModTags.INCORRECT_FOR_MITHRIL_TOOL)
        .addOptionalTag(BlockTags.NEEDS_DIAMOND_TOOL)
        .addOptionalTag(ModTags.NEEDS_NETHERITE_TOOL)
        .addOptionalTag(ModTags.NEEDS_ENDERIUM_TOOL)
        .addOptionalTag(ModTags.NEEDS_TENEBRIS_TOOL)
        .addOptionalTag(ModTags.NEEDS_ZENITH_TOOL);

        replace(valueLookupBuilder(BlockTags.INCORRECT_FOR_DIAMOND_TOOL))
        .addOptionalTag(ModTags.NEEDS_NETHERITE_TOOL)
        .addOptionalTag(ModTags.NEEDS_ENDERIUM_TOOL)
        .addOptionalTag(ModTags.NEEDS_TENEBRIS_TOOL)
        .addOptionalTag(ModTags.NEEDS_ZENITH_TOOL);

        replace(valueLookupBuilder(BlockTags.INCORRECT_FOR_NETHERITE_TOOL))
        .addOptionalTag(ModTags.NEEDS_ENDERIUM_TOOL)
        .addOptionalTag(ModTags.NEEDS_TENEBRIS_TOOL)
        .addOptionalTag(ModTags.NEEDS_ZENITH_TOOL);

        valueLookupBuilder(ModTags.INCORRECT_FOR_ENDERIUM_TOOL)
        .addOptionalTag(ModTags.NEEDS_TENEBRIS_TOOL)
        .addOptionalTag(ModTags.NEEDS_ZENITH_TOOL);

        valueLookupBuilder(ModTags.INCORRECT_FOR_TENEBRIS_TOOL)
        .addOptionalTag(ModTags.NEEDS_ZENITH_TOOL);

        valueLookupBuilder(ModTags.INCORRECT_FOR_ZENITH_TOOL);
    }

    @SuppressWarnings("unchecked")
    private static <E, T> ProvidedTagBuilder<E, T> replace(ProvidedTagBuilder<E, T> b) {
        ((FabricProvidedTagBuilder<E, T>) (Object) b).setReplace(true);
        return b;
    }
}
